const mongoose = require("mongoose");

const unresolvedMenteePaymentsSchema = new mongoose.Schema({
  isConsentPayment: String,
  mihpayid: String,
  mode: String,
  status: String,
  unmappedstatus: String,
  txnid: String,
  amount: String,
  addedon: String,
  productinfo: String,
  firstname: String,
  lastname: String,
  address1: String,
  address2: String,
  city: String,
  state: String,
  country: String,
  zipcode: String,
  email: String,
  phone: String,
  udf1: String,
  udf2: String,
  udf3: String,
  udf4: String,
  udf5: String,
  udf6: String,
  udf7: String,
  udf8: String,
  udf9: String,
  udf10: String,
  field1: String,
  field2: String,
  field3: String,
  field4: String,
  field5: String,
  field6: String,
  field7: String,
  field8: String,
  field9: String,
  giftCardIssued: String,
  PG_TYPE: String,
  encryptedPaymentId: String,
  bank_ref_num: String,
  bankcode: String,
  error: String,
  error_Message: String,
  name_on_card: String,
  cardnum: String,
  amount_split: String,
  payuMoneyId: String,
  discount: String,
  net_amount_debit: String,
});

module.exports = mongoose.model(
  "UnresolvedMenteePayments",
  unresolvedMenteePaymentsSchema
);
